// Hidden test for PR #26 T2 atomic bid core
// Generated by PDGGK reviewer (bug-free standard 5.23 02:09)
// Coverage gap vs PR #27: PR #27 has no REST/API facts-gate coverage; this
// verifies freeze before confirmed AI facts returns ERR_FACTS_NOT_CONFIRMED.
// Run: TARGET=http://localhost:8080 go test -run TestT2HiddenFactsGateFreezeRequiresConfirmedFacts ./apps/lumen/internal/server/...
package server

import (
	"encoding/json"
	"net/http"
	"os"
	"testing"
	"time"

	"github.com/Eliaaazzz/live-auction-system/apps/lumen/internal/model"
)

func TestT2HiddenFactsGateFreezeRequiresConfirmedFacts(t *testing.T) {
	target := os.Getenv("TARGET")
	if target == "" {
		target, _ = startTestServer(t) // in-process stack so this never skips in CI
	}
	hc := &http.Client{Timeout: 5 * time.Second}
	seller, err := devLogin(hc, target, "Hidden Facts Seller", "seller")
	if err != nil {
		t.Fatalf("dev login: %v", err)
	}
	productID, err := createProduct(hc, target, seller.Token)
	if err != nil {
		t.Fatalf("create product: %v", err)
	}

	var created struct {
		AuctionID string `json:"auctionId"`
	}
	body := map[string]any{
		"productId": productID,
		"rules": model.Rules{
			StartPriceCents: 10000, IncrementCents: 1000, CapPriceCents: 0,
			DurationSec: 60, ExtendWindowSec: 10, ExtendSec: 10,
		},
		"factsConfirmed": false,
	}
	if err := postJSON(hc, target+"/api/auctions", seller.Token, body, &created); err != nil {
		t.Fatalf("create auction with unconfirmed facts: %v", err)
	}

	resp, data, err := postJSONRaw(hc, target+"/api/auctions/"+created.AuctionID+"/freeze", seller.Token, nil)
	if err != nil {
		t.Fatalf("freeze: %v", err)
	}
	if resp.StatusCode != http.StatusConflict {
		t.Fatalf("freeze status=%d body=%s want 409", resp.StatusCode, string(data))
	}
	var out struct {
		Code string `json:"code"`
	}
	if err := json.Unmarshal(data, &out); err != nil {
		t.Fatalf("decode freeze body: %v body=%s", err, string(data))
	}
	if out.Code != model.CodeErrFacts {
		t.Fatalf("freeze code=%s want %s", out.Code, model.CodeErrFacts)
	}

	var snap model.RoomSnapshotData
	if err := getJSON(hc, target+"/api/auctions/"+created.AuctionID, &snap); err != nil {
		t.Fatalf("get auction: %v", err)
	}
	if snap.Status != model.StateDraft {
		t.Fatalf("after failed freeze status=%s want DRAFT", snap.Status)
	}
}
