// Hidden test for PR #26 T2 atomic bid core
// Generated by PDGGK reviewer (bug-free standard 5.23 02:09)
// Coverage gap vs PR #27: PR #27 is store/Lua-only; this exercises the WS
// dispatch path for malformed BID_PLACE, bad money strings, oversized
// clientBidId, binary-ish invalid JSON data, and frame-limit constants.
// Run: go test -run TestT2HiddenWS ./apps/lumen/internal/server/...
package server

import (
	"context"
	"encoding/json"
	"strings"
	"testing"
	"time"

	"github.com/Eliaaazzz/live-auction-system/apps/lumen/internal/model"
)

func TestT2HiddenWSDispatchRejectsMalformedBidPlaceAsBadInput(t *testing.T) {
	cases := []struct {
		name string
		aid  string
		data json.RawMessage
	}{
		{
			name: "missing room",
			aid:  "",
			data: mustJSON(t, model.BidPlaceData{ClientBidID: "cb", AmountCents: "11000"}),
		},
		{
			name: "missing clientBidId",
			aid:  "auc_hidden",
			data: mustJSON(t, model.BidPlaceData{AmountCents: "11000"}),
		},
		{
			name: "empty amount",
			aid:  "auc_hidden",
			data: mustJSON(t, model.BidPlaceData{ClientBidID: "cb", AmountCents: ""}),
		},
		{
			name: "zero amount",
			aid:  "auc_hidden",
			data: mustJSON(t, model.BidPlaceData{ClientBidID: "cb", AmountCents: "0"}),
		},
		{
			name: "negative amount",
			aid:  "auc_hidden",
			data: mustJSON(t, model.BidPlaceData{ClientBidID: "cb", AmountCents: "-1"}),
		},
		{
			name: "non numeric",
			aid:  "auc_hidden",
			data: mustJSON(t, model.BidPlaceData{ClientBidID: "cb", AmountCents: "not-cents"}),
		},
		{
			name: "overflow int64",
			aid:  "auc_hidden",
			data: mustJSON(t, model.BidPlaceData{ClientBidID: "cb", AmountCents: "9223372036854775808"}),
		},
		{
			name: "trailing space",
			aid:  "auc_hidden",
			data: mustJSON(t, model.BidPlaceData{ClientBidID: "cb", AmountCents: "11000 "}),
		},
		{
			name: "binary invalid json data",
			aid:  "auc_hidden",
			data: json.RawMessage{0xff, 0xfe, 0xfd},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			env := model.Envelope{Type: model.TypeBidPlace, ServerTimeMs: time.Now().UnixMilli(), Data: tc.data}
			got := dispatchHiddenWS(t, tc.aid, env)
			assertHiddenRejected(t, got, model.CodeErrBadInput)
		})
	}
}

func TestT2HiddenWSDispatchRejectsOversizedClientBidIDBeforeStoreCall(t *testing.T) {
	data := mustJSON(t, model.BidPlaceData{
		ClientBidID: strings.Repeat("x", maxClientBidIDLen+1),
		AmountCents: "11000",
	})
	got := dispatchHiddenWS(t, "auc_hidden", model.Envelope{Type: model.TypeBidPlace, ServerTimeMs: time.Now().UnixMilli(), Data: data})
	assertHiddenRejected(t, got, model.CodeErrBadInput)
}

func TestT2HiddenWSFrameLimitConstants(t *testing.T) {
	if maxWSFrameBytes != 32*1024 {
		t.Fatalf("maxWSFrameBytes=%d want 32768", maxWSFrameBytes)
	}
	if maxClientBidIDLen != 128 {
		t.Fatalf("maxClientBidIDLen=%d want 128", maxClientBidIDLen)
	}
	if len(strings.Repeat("x", maxWSFrameBytes+1)) <= maxWSFrameBytes {
		t.Fatalf("oversized payload fixture did not exceed frame limit")
	}
}

func dispatchHiddenWS(t *testing.T, aid string, env model.Envelope) model.Envelope {
	t.Helper()
	s := &Server{}
	c := &Conn{send: make(chan []byte, 1), aid: aid, userID: "hidden_user", displayName: "Hidden User"}
	s.dispatchWS(context.Background(), c, env)
	select {
	case raw := <-c.send:
		var out model.Envelope
		if err := json.Unmarshal(raw, &out); err != nil {
			t.Fatalf("decode pushed envelope: %v; raw=%s", err, string(raw))
		}
		return out
	default:
		t.Fatalf("dispatchWS did not push a rejection")
		return model.Envelope{}
	}
}

func assertHiddenRejected(t *testing.T, env model.Envelope, code string) {
	t.Helper()
	if env.Type != model.TypeBidRejected {
		t.Fatalf("env type=%s want BID_REJECTED", env.Type)
	}
	var data model.BidRejectedData
	if err := json.Unmarshal(env.Data, &data); err != nil {
		t.Fatalf("decode rejected data: %v", err)
	}
	if data.Code != code {
		t.Fatalf("rejected code=%s want %s", data.Code, code)
	}
}

func mustJSON(t *testing.T, v any) json.RawMessage {
	t.Helper()
	raw, err := json.Marshal(v)
	if err != nil {
		t.Fatal(err)
	}
	return raw
}
