// Hidden test for PR #26 T2 atomic bid core
// Generated by PDGGK reviewer (bug-free standard 5.23 02:09)
// Coverage gap vs PR #27: PR #27 has no seqguard tests; this adds seq=0,
// max-int64, forward-gap, and high-volume monotonic client-side guard edges.
// Run: go test -run TestT2HiddenSeqGuard ./apps/lumen/internal/seqguard/...
package seqguard

import (
	"math"
	"testing"
)

func TestT2HiddenSeqGuardZeroAndMaxInt64Boundaries(t *testing.T) {
	g := New(math.MaxInt64 - 1)
	if got := g.Gap(math.MaxInt64); got != 0 {
		t.Fatalf("Gap(maxInt64) from maxInt64-1=%d want 0", got)
	}
	if !g.Apply(math.MaxInt64) {
		t.Fatalf("Apply(maxInt64) should apply from maxInt64-1")
	}
	if g.Last() != math.MaxInt64 {
		t.Fatalf("Last()=%d want maxInt64", g.Last())
	}
	if g.Apply(math.MaxInt64) {
		t.Fatalf("duplicate maxInt64 should be dropped")
	}
	if got := g.Gap(math.MaxInt64); got != 0 {
		t.Fatalf("Gap(duplicate maxInt64)=%d want 0", got)
	}
	if !g.Apply(0) || !g.Apply(-1) {
		t.Fatalf("seq<=0 control frames should always apply")
	}
	if g.Last() != math.MaxInt64 {
		t.Fatalf("control frames changed Last()=%d want maxInt64", g.Last())
	}
}

func TestT2HiddenSeqGuardGapIsPureAndLateCatchupDrops(t *testing.T) {
	g := New(100)
	if got := g.Gap(105); got != 4 {
		t.Fatalf("Gap(105)=%d want 4", got)
	}
	if g.Last() != 100 {
		t.Fatalf("Gap advanced Last()=%d want 100", g.Last())
	}
	if !g.Apply(105) {
		t.Fatalf("forward jump should apply in T2 guard contract")
	}
	for s := int64(101); s <= 104; s++ {
		if g.Apply(s) {
			t.Fatalf("late catchup seq %d after jump should be stale and dropped", s)
		}
	}
	if g.Last() != 105 {
		t.Fatalf("Last()=%d want 105", g.Last())
	}
}

func TestT2HiddenSeqGuardMonotonicUnderLoad(t *testing.T) {
	g := New(0)
	for s := int64(1); s <= 100_000; s++ {
		if !g.Apply(s) {
			t.Fatalf("Apply(%d)=false want true", s)
		}
		if g.Apply(s) {
			t.Fatalf("duplicate Apply(%d)=true want false", s)
		}
	}
	if g.Last() != 100_000 {
		t.Fatalf("Last()=%d want 100000", g.Last())
	}
}
