// Hidden test for PR #26 T2 atomic bid core
// Generated by PDGGK reviewer (bug-free standard 5.23 02:09)
// Coverage gap vs PR #27: PR #27 covers duplicate-after-extend; this covers
// duplicate-after-SOLD ordering and the no-rollback hazard when explicit Stream
// ID state is inconsistent before XADD.
// Run: go test -run 'TestT2Hidden(DuplicateAfterSold|StreamIDConflict)' ./apps/lumen/internal/store/...
package store

import (
	"context"
	"testing"

	"github.com/redis/go-redis/v9"

	"github.com/Eliaaazzz/live-auction-system/apps/lumen/internal/model"
)

func TestT2HiddenDuplicateAfterSoldReturnsCachedAckBeforeTerminalGuard(t *testing.T) {
	s := newTestStore(t)
	ctx := context.Background()
	r := defaultRules()
	r.CapPriceCents = 12000
	aid := liveAuction(t, s, r, 60_000)

	code, seq, firstPayload, err := s.PlaceBid(ctx, aid, "buyer1", "sold_cb", "12000", "Buyer 1")
	if err != nil || code != model.CodeOKSold || seq != 1 {
		t.Fatalf("cap bid: code=%s seq=%d err=%v want OK_SOLD/1", code, seq, err)
	}
	code, seq, dupPayload, err := s.PlaceBid(ctx, aid, "buyer1", "sold_cb", "11999", "Buyer 1")
	if err != nil || code != model.CodeDuplicate || seq != 0 {
		t.Fatalf("duplicate after SOLD: code=%s seq=%d err=%v want DUPLICATE/0", code, seq, err)
	}
	if dupPayload != firstPayload {
		t.Fatalf("duplicate after SOLD payload changed:\nfirst=%s\ndup=%s", firstPayload, dupPayload)
	}
	events, _, err := s.ReadEventsAfter(ctx, aid, "")
	if err != nil {
		t.Fatal(err)
	}
	if len(events) != 2 || events[0].Type != model.TypeBidAccepted || events[1].Type != model.TypeAuctionSold {
		t.Fatalf("duplicate after SOLD changed stream: %+v", events)
	}

	code, seq, _, err = s.PlaceBid(ctx, aid, "buyer2", "fresh_after_sold", "12000", "Buyer 2")
	if err != nil || code != model.CodeErrNotLive || seq != 0 {
		t.Fatalf("fresh bid after SOLD: code=%s seq=%d err=%v want ERR_NOT_LIVE/0", code, seq, err)
	}
}

func TestT2HiddenStreamIDConflictDoesNotDirtyWrite(t *testing.T) {
	s := newTestStore(t)
	ctx := context.Background()
	aid := liveAuction(t, s, defaultRules(), 60_000)

	if err := s.rdb.XAdd(ctx, &redis.XAddArgs{
		Stream: streamKey(aid),
		ID:     "1-0",
		Values: map[string]any{"type": model.TypeBidAccepted, "seq": 1, "payload": `{}`},
	}).Err(); err != nil {
		t.Fatal(err)
	}
	// RECONCILED with the M1 fix: the original expected a raw XADD error AFTER
	// dirty writes. place_bid.lua now preflights stream-vs-state seq lockstep
	// BEFORE any mutation, so a desynced stream (last id 1-0 while state.seq=0)
	// returns a clean ERR_INTERNAL with no dirty write — the guarantee this wants.
	code, seq, payload, err := s.PlaceBid(ctx, aid, "u1", "xadd_conflict_cb", "11000", "U1")
	if err != nil || code != model.CodeErrInternal || seq != 0 || payload != "" {
		t.Fatalf("XADD desync: code=%s seq=%d payload=%q err=%v want ERR_INTERNAL/0/empty (clean preflight)", code, seq, payload, err)
	}
	snap, snapErr := s.Snapshot(ctx, aid)
	if snapErr != nil {
		t.Fatal(snapErr)
	}
	if snap.CurrentPriceCents != "10000" || snap.WinnerID != "" || snap.Seq != 0 {
		t.Fatalf("XADD conflict left dirty state: %+v; err=%v", snap, err)
	}
	if z, _ := s.rdb.ZCard(ctx, lbKey(aid)).Result(); z != 0 {
		t.Fatalf("XADD conflict wrote leaderboard rows=%d want 0", z)
	}
	if exists, _ := s.rdb.HExists(ctx, dedupeKey(aid, "u1"), "xadd_conflict_cb").Result(); exists {
		t.Fatalf("XADD conflict wrote dedupe cache")
	}
}
