// Hidden test for PR #26 T2 atomic bid core
// Generated by PDGGK reviewer (bug-free standard 5.23 02:09).
//
// RECONCILED by integrator (@Eliaaazzz) with H2's primary fix option: PDGGK's
// finding H2 offered (a) cap money at 2^53-1 OR (b) redesign Lua/ZSET storage to
// keep >2^53 exact. The original test asserted (b), but a Redis ZSET score is a
// float64 — the leaderboard cannot preserve >2^53 exactly under any storage. So
// we took (a): values up to MaxMoneyCents (2^53-1) are stored string-exact;
// above it is rejected. This test now pins that boundary on both sides.
// Run: go test -run TestT2HiddenMoneyExactToMaxCentsAndRejectsAbove ./apps/lumen/internal/store/...
package store

import (
	"context"
	"strconv"
	"strings"
	"testing"

	"github.com/Eliaaazzz/live-auction-system/apps/lumen/internal/model"
)

func TestT2HiddenMoneyExactToMaxCentsAndRejectsAbove(t *testing.T) {
	s := newTestStore(t)
	ctx := context.Background()
	aid := liveAuction(t, s, defaultRules(), 60_000)

	// MaxMoneyCents (2^53-1) is the largest value exactly representable as float64,
	// so it must round-trip exactly through ack payload, Redis state, and ZSET score.
	maxMoney := strconv.FormatInt(int64(model.MaxMoneyCents), 10) // "9007199254740991"
	code, seq, payload, err := s.PlaceBid(ctx, aid, "big_money_user", "big_money_cb", maxMoney, "Big Money")
	if err != nil || code != model.CodeOKAccepted || seq != 1 {
		t.Fatalf("max-money bid: code=%s seq=%d err=%v want OK_ACCEPTED/1", code, seq, err)
	}
	if !strings.Contains(payload, `"amountCents":"`+maxMoney+`"`) {
		t.Fatalf("ack payload lost exact money string: %s", payload)
	}
	snap, err := s.Snapshot(ctx, aid)
	if err != nil {
		t.Fatal(err)
	}
	if snap.CurrentPriceCents != maxMoney {
		t.Fatalf("Redis state currentPriceCents=%q want exact %q", snap.CurrentPriceCents, maxMoney)
	}
	lb, err := s.Leaderboard(ctx, aid, 1)
	if err != nil {
		t.Fatal(err)
	}
	if len(lb) != 1 || lb[0].AmountCents != maxMoney {
		t.Fatalf("leaderboard=%+v want exact amountCents %q", lb, maxMoney)
	}

	// Above MaxMoneyCents (2^53+1) loses float64 integer precision, so it is
	// rejected (gateway maps this to ERR_BAD_INPUT; the Lua defensive ceiling
	// reached directly here returns ERR_TOO_LOW). No silent precision loss.
	code, _, _, err = s.PlaceBid(ctx, aid, "u2", "above_cb", "9007199254740993", "U2")
	if err != nil || code != model.CodeErrTooLow {
		t.Fatalf("above-max bid: code=%s err=%v want ERR_TOO_LOW (no >2^53 acceptance)", code, err)
	}
}
