// Hidden test for PR #26 T2 atomic bid core
// Generated by PDGGK reviewer (bug-free standard 5.23 02:09)
// Coverage gap vs PR #27: PR #27 covers duplicate-after-extend shape; this
// covers dedupe TTL behavior before expiry and after expiry without waiting 24h.
// Run: go test -run TestT2HiddenDedupeTTLBeforeAndAfterExpiry ./apps/lumen/internal/store/...
package store

import (
	"context"
	"testing"
	"time"

	"github.com/Eliaaazzz/live-auction-system/apps/lumen/internal/model"
)

func TestT2HiddenDedupeTTLBeforeAndAfterExpiry(t *testing.T) {
	s := newTestStore(t)
	ctx := context.Background()
	aid := liveAuction(t, s, defaultRules(), 60_000)
	key := dedupeKey(aid, "ttl_user")

	code, seq, firstPayload, err := s.PlaceBid(ctx, aid, "ttl_user", "ttl_cb", "11000", "TTL User")
	if err != nil || code != model.CodeOKAccepted || seq != 1 {
		t.Fatalf("first bid: code=%s seq=%d err=%v", code, seq, err)
	}
	if ttl, _ := s.rdb.TTL(ctx, key).Result(); ttl <= 0 || ttl > 24*time.Hour {
		t.Fatalf("initial dedupe ttl=%s want (0,24h]", ttl)
	}

	// Simulate the 24h-1s side of the boundary by forcing the key close to expiry:
	// retry still returns the original cached ack and must not mutate price/seq.
	if err := s.rdb.Expire(ctx, key, 24*time.Hour-time.Second).Err(); err != nil {
		t.Fatal(err)
	}
	code, seq, dupPayload, err := s.PlaceBid(ctx, aid, "ttl_user", "ttl_cb", "99000", "TTL User")
	if err != nil || code != model.CodeDuplicate || seq != 0 {
		t.Fatalf("before expiry retry: code=%s seq=%d err=%v want DUPLICATE seq=0", code, seq, err)
	}
	if dupPayload != firstPayload {
		t.Fatalf("duplicate payload changed:\nfirst=%s\ndup=%s", firstPayload, dupPayload)
	}
	if snap, _ := s.Snapshot(ctx, aid); snap.CurrentPriceCents != "11000" || snap.Seq != 1 {
		t.Fatalf("duplicate before expiry mutated snapshot: %+v", snap)
	}

	// Simulate the 24h+1s side by expiring the dedupe key. The same clientBidId is
	// no longer cached, so a valid higher bid is accepted as a new bid.
	if err := s.rdb.Expire(ctx, key, time.Second).Err(); err != nil {
		t.Fatal(err)
	}
	time.Sleep(1200 * time.Millisecond)
	if exists, _ := s.rdb.Exists(ctx, key).Result(); exists != 0 {
		t.Fatalf("dedupe key still exists after forced expiry")
	}
	code, seq, secondPayload, err := s.PlaceBid(ctx, aid, "ttl_user", "ttl_cb", "12000", "TTL User")
	if err != nil || code != model.CodeOKAccepted || seq != 2 {
		t.Fatalf("after expiry retry: code=%s seq=%d err=%v want OK_ACCEPTED seq=2", code, seq, err)
	}
	if secondPayload == firstPayload {
		t.Fatalf("post-expiry bid replayed old payload instead of accepting a new bid")
	}
}

func TestT2HiddenDedupePersistedKeyGets24hTTLOnDuplicate(t *testing.T) {
	s := newTestStore(t)
	ctx := context.Background()
	aid := liveAuction(t, s, defaultRules(), 60_000)
	key := dedupeKey(aid, "persist_user")

	if code, _, _, err := s.PlaceBid(ctx, aid, "persist_user", "persist_cb", "11000", "Persist User"); err != nil || code != model.CodeOKAccepted {
		t.Fatalf("first bid: code=%s err=%v", code, err)
	}
	if err := s.rdb.Persist(ctx, key).Err(); err != nil {
		t.Fatal(err)
	}
	if ttl, _ := s.rdb.TTL(ctx, key).Result(); ttl != -1 {
		t.Fatalf("test setup ttl=%s want -1", ttl)
	}
	if code, _, _, err := s.PlaceBid(ctx, aid, "persist_user", "persist_cb", "12000", "Persist User"); err != nil || code != model.CodeDuplicate {
		t.Fatalf("duplicate on persisted key: code=%s err=%v want DUPLICATE", code, err)
	}
	if ttl, _ := s.rdb.TTL(ctx, key).Result(); ttl <= 0 || ttl > 24*time.Hour {
		t.Fatalf("duplicate should restore bounded ttl; got %s", ttl)
	}
}
