// Hidden test for PR #26 T2 atomic bid core
// Generated by PDGGK reviewer (bug-free standard 5.23 02:09)
// Coverage gap vs PR #27: PR #27 covers cap-hit inside anti-snipe and past-end
// rejection; this covers the cap exact/over-cap pair, over-cap side effects, and
// both sides of the Redis-TIME anti-snipe/end boundary without a flaky 1ms sleep.
// Run: go test -run 'TestT2Hidden(CapExactBoundaryAndOverCapNoSideEffects|AntiSnipeBoundaryInsideWindowAndAfterEnd)' ./apps/lumen/internal/store/...
package store

import (
	"context"
	"testing"

	"github.com/Eliaaazzz/live-auction-system/apps/lumen/internal/model"
)

func TestT2HiddenCapExactBoundaryAndOverCapNoSideEffects(t *testing.T) {
	s := newTestStore(t)
	ctx := context.Background()

	r := defaultRules()
	r.CapPriceCents = 12000
	overCapAID := liveAuction(t, s, r, 60_000)
	code, seq, payload, err := s.PlaceBid(ctx, overCapAID, "u1", "over_cap_cb", "12001", "U1")
	if err != nil || code != model.CodeErrTooLow || seq != 0 || payload != "" {
		t.Fatalf("over cap: code=%s seq=%d payload=%q err=%v want ERR_TOO_LOW/0/empty", code, seq, payload, err)
	}
	if got, _ := s.rdb.HGet(ctx, stateKey(overCapAID), "seq").Int64(); got != 0 {
		t.Fatalf("over-cap rejection advanced seq=%d want 0", got)
	}
	if z, _ := s.rdb.ZCard(ctx, lbKey(overCapAID)).Result(); z != 0 {
		t.Fatalf("over-cap rejection wrote leaderboard rows=%d want 0", z)
	}
	if exists, _ := s.rdb.HExists(ctx, dedupeKey(overCapAID, "u1"), "over_cap_cb").Result(); exists {
		t.Fatalf("over-cap rejection poisoned dedupe cache")
	}
	code, seq, _, err = s.PlaceBid(ctx, overCapAID, "u1", "over_cap_cb", "11000", "U1")
	if err != nil || code != model.CodeOKAccepted || seq != 1 {
		t.Fatalf("retry same clientBidId with valid amount: code=%s seq=%d err=%v want OK_ACCEPTED/1", code, seq, err)
	}

	exactCapAID := liveAuction(t, s, r, 60_000)
	code, seq, payload, err = s.PlaceBid(ctx, exactCapAID, "u2", "exact_cap_cb", "12000", "U2")
	if err != nil || code != model.CodeOKSold || seq != 1 || payload == "" {
		t.Fatalf("exact cap: code=%s seq=%d payload=%q err=%v want OK_SOLD/1/nonempty", code, seq, payload, err)
	}
	if st, _ := s.rdb.HGet(ctx, stateKey(exactCapAID), "status").Result(); st != model.StateSold {
		t.Fatalf("exact cap status=%s want SOLD", st)
	}
}

func TestT2HiddenAntiSnipeBoundaryInsideWindowAndAfterEnd(t *testing.T) {
	s := newTestStore(t)
	ctx := context.Background()
	r := defaultRules()
	r.ExtendWindowSec = 1
	r.ExtendSec = 5
	r.MaxExtensions = 1

	insideAID := liveAuction(t, s, r, 60_000)
	redisNow, err := s.rdb.Time(ctx).Result()
	if err != nil {
		t.Fatal(err)
	}
	if err := s.rdb.HSet(ctx, stateKey(insideAID), "endAtMs", redisNow.UnixMilli()+500).Err(); err != nil {
		t.Fatal(err)
	}
	code, seq, _, err := s.PlaceBid(ctx, insideAID, "u1", "inside_cb", "11000", "U1")
	if err != nil || code != model.CodeOKExtended || seq != 1 {
		t.Fatalf("inside extend window: code=%s seq=%d err=%v want OK_EXTENDED/1", code, seq, err)
	}

	afterAID := liveAuction(t, s, r, 60_000)
	redisNow, err = s.rdb.Time(ctx).Result()
	if err != nil {
		t.Fatal(err)
	}
	if err := s.rdb.HSet(ctx, stateKey(afterAID), "endAtMs", redisNow.UnixMilli()-1).Err(); err != nil {
		t.Fatal(err)
	}
	code, seq, _, err = s.PlaceBid(ctx, afterAID, "u2", "after_cb", "11000", "U2")
	if err != nil || code != model.CodeErrAfterEnd || seq != 0 {
		t.Fatalf("after end boundary: code=%s seq=%d err=%v want ERR_AFTER_END/0", code, seq, err)
	}
}
