// Hidden test for PR #26 T2 atomic bid core
// Generated by PDGGK reviewer (bug-free standard 5.23 02:09)
// Coverage gap vs PR #27: PR #27 covers sequential extension stream IDs and
// max-extension absence/semantics; this adds concurrent accepted bids while the
// maxExtensions boundary is being hit, then verifies stream seq gap-free.
// Run: go test -run TestT2HiddenConcurrentExtendsStopAtMaxExtensionsNoSeqGaps ./apps/lumen/internal/store/...
package store

import (
	"context"
	"fmt"
	"sort"
	"strconv"
	"sync"
	"testing"

	"github.com/Eliaaazzz/live-auction-system/apps/lumen/internal/model"
)

func TestT2HiddenConcurrentExtendsStopAtMaxExtensionsNoSeqGaps(t *testing.T) {
	s := newTestStore(t)
	ctx := context.Background()
	r := defaultRules()
	r.ExtendWindowSec = 3600
	r.ExtendSec = 10
	r.MaxExtensions = 3
	aid := liveAuction(t, s, r, 60_000)

	const bidders = 12
	var wg sync.WaitGroup
	var mu sync.Mutex
	bidSeqs := make([]int64, 0, bidders)
	extended := 0

	for i := 0; i < bidders; i++ {
		wg.Add(1)
		go func(i int) {
			defer wg.Done()
			uid := fmt.Sprintf("hidden_u_%02d", i)
			for attempt := 0; attempt < 200; attempt++ {
				snap, err := s.Snapshot(ctx, aid)
				if err != nil {
					t.Errorf("snapshot: %v", err)
					return
				}
				amount := strconv.FormatInt(parseInt(snap.CurrentPriceCents)+1000, 10)
				code, seq, _, err := s.PlaceBid(ctx, aid, uid, fmt.Sprintf("hidden_cb_%02d_%03d", i, attempt), amount, uid)
				if err != nil {
					t.Errorf("place bid: %v", err)
					return
				}
				switch code {
				case model.CodeOKAccepted, model.CodeOKExtended:
					mu.Lock()
					bidSeqs = append(bidSeqs, seq)
					if code == model.CodeOKExtended {
						extended++
					}
					mu.Unlock()
					return
				case model.CodeErrTooLow:
					continue
				default:
					t.Errorf("unexpected code %s", code)
					return
				}
			}
			t.Errorf("%s never landed an accepted bid", uid)
		}(i)
	}
	wg.Wait()

	if len(bidSeqs) != bidders {
		t.Fatalf("accepted bids=%d want %d", len(bidSeqs), bidders)
	}
	if extended != int(r.MaxExtensions) {
		t.Fatalf("OK_EXTENDED count=%d want maxExtensions=%d", extended, r.MaxExtensions)
	}
	if got, _ := s.rdb.HGet(ctx, stateKey(aid), "extendCount").Int64(); got != r.MaxExtensions {
		t.Fatalf("extendCount=%d want %d", got, r.MaxExtensions)
	}

	events, _, err := s.ReadEventsAfter(ctx, aid, "")
	if err != nil {
		t.Fatal(err)
	}
	wantEvents := bidders + int(r.MaxExtensions)
	if len(events) != wantEvents {
		t.Fatalf("stream events=%d want accepted(%d)+extensions(%d)=%d", len(events), bidders, r.MaxExtensions, wantEvents)
	}
	extendedEvents := 0
	for i, e := range events {
		wantSeq := int64(i + 1)
		if e.Seq != wantSeq || e.ID != fmt.Sprintf("%d-0", wantSeq) {
			t.Fatalf("event[%d]=%+v want seq/id %d/%d-0", i, e, wantSeq, wantSeq)
		}
		if e.Type == model.TypeAuctionExtended {
			extendedEvents++
		}
	}
	if extendedEvents != int(r.MaxExtensions) {
		t.Fatalf("AUCTION_EXTENDED events=%d want %d", extendedEvents, r.MaxExtensions)
	}
	sort.Slice(bidSeqs, func(i, j int) bool { return bidSeqs[i] < bidSeqs[j] })
	if bidSeqs[0] != 1 {
		t.Fatalf("first bid seq=%d want 1 (seqs=%v)", bidSeqs[0], bidSeqs)
	}
	if stateSeq, _ := s.rdb.HGet(ctx, stateKey(aid), "seq").Int64(); stateSeq != int64(wantEvents) {
		t.Fatalf("state seq=%d want %d", stateSeq, wantEvents)
	}
}
