// Hidden test for PR #26 T2 atomic bid core
// Generated by PDGGK reviewer (bug-free standard 5.23 02:09)
// Coverage gap vs PR #27: PR #27 covers cap=0 with a large but still
// double-exact-ish amount; this covers the money-as-string/int64 contract above
// JavaScript/Lua double precision and checks Redis state plus leaderboard.
// Run: go test -run TestT2HiddenMoneyStringAboveDoublePrecisionStaysExact ./apps/lumen/internal/store/...
package store

import (
	"context"
	"strings"
	"testing"

	"github.com/Eliaaazzz/live-auction-system/apps/lumen/internal/model"
)

func TestT2HiddenMoneyStringAboveDoublePrecisionStaysExact(t *testing.T) {
	s := newTestStore(t)
	ctx := context.Background()
	aid := liveAuction(t, s, defaultRules(), 60_000)

	const amount = "9007199254740993" // 2^53 + 1: valid int64, not exactly representable as float64/Lua number.
	code, seq, payload, err := s.PlaceBid(ctx, aid, "big_money_user", "big_money_cb", amount, "Big Money")
	if err != nil || code != model.CodeOKAccepted || seq != 1 {
		t.Fatalf("large money bid: code=%s seq=%d err=%v want OK_ACCEPTED/1", code, seq, err)
	}
	if !strings.Contains(payload, `"amountCents":"`+amount+`"`) {
		t.Fatalf("ack payload lost exact money string: %s", payload)
	}
	snap, err := s.Snapshot(ctx, aid)
	if err != nil {
		t.Fatal(err)
	}
	if snap.CurrentPriceCents != amount {
		t.Fatalf("Redis state currentPriceCents=%q want exact %q", snap.CurrentPriceCents, amount)
	}
	lb, err := s.Leaderboard(ctx, aid, 1)
	if err != nil {
		t.Fatal(err)
	}
	if len(lb) != 1 || lb[0].AmountCents != amount {
		t.Fatalf("leaderboard=%+v want exact amountCents %q", lb, amount)
	}
}
