// Hidden test for PR #26 T2 atomic bid core
// Generated by PDGGK reviewer (bug-free standard 5.23 02:09)
// Coverage gap vs PR #27: PR #27 poisons only one hot key type and checks SOLD
// indirectly; this covers every Lua hot key type plus every canonical terminal
// status (SOLD/NO_BID/CANCELLED/ORDER_CREATED) rejecting bids without seq writes.
// Run: go test -run 'TestT2Hidden(TypeGuardAllHotKeysNoMutation|EveryTerminalStatusRejectsBid)' ./apps/lumen/internal/store/...
package store

import (
	"context"
	"testing"

	"github.com/Eliaaazzz/live-auction-system/apps/lumen/internal/model"
)

func TestT2HiddenTypeGuardAllHotKeysNoMutation(t *testing.T) {
	cases := []struct {
		name      string
		poisonKey func(aid string) string
	}{
		{name: "state", poisonKey: stateKey},
		{name: "leaderboard", poisonKey: lbKey},
		{name: "stream", poisonKey: streamKey},
		{name: "dedupe", poisonKey: func(aid string) string { return dedupeKey(aid, "u1") }},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			s := newTestStore(t)
			ctx := context.Background()
			aid := liveAuction(t, s, defaultRules(), 60_000)
			key := tc.poisonKey(aid)

			if err := s.rdb.Del(ctx, key).Err(); err != nil {
				t.Fatal(err)
			}
			if err := s.rdb.Set(ctx, key, "wrong-type", 0).Err(); err != nil {
				t.Fatal(err)
			}

			code, seq, payload, err := s.PlaceBid(ctx, aid, "u1", "cb_guard", "11000", "U1")
			if err != nil || code != model.CodeErrInternal || seq != 0 || payload != "" {
				t.Fatalf("code=%s seq=%d payload=%q err=%v want ERR_INTERNAL/0/empty", code, seq, payload, err)
			}
			if typ, _ := s.rdb.Type(ctx, key).Result(); typ != "string" {
				t.Fatalf("poisoned key type=%s want string", typ)
			}
			if tc.name != "state" {
				if got, _ := s.rdb.HGet(ctx, stateKey(aid), "seq").Int64(); got != 0 {
					t.Fatalf("type guard on %s advanced seq=%d want 0", tc.name, got)
				}
			}
		})
	}
}

func TestT2HiddenEveryTerminalStatusRejectsBid(t *testing.T) {
	for _, status := range []string{model.StateSold, model.StateNoBid, model.StateCancelled, model.StateOrderCreated} {
		t.Run(status, func(t *testing.T) {
			s := newTestStore(t)
			ctx := context.Background()
			aid := liveAuction(t, s, defaultRules(), 60_000)
			if err := s.rdb.HSet(ctx, stateKey(aid), "status", status).Err(); err != nil {
				t.Fatal(err)
			}

			code, seq, payload, err := s.PlaceBid(ctx, aid, "u1", "cb_terminal", "11000", "U1")
			if err != nil || code != model.CodeErrNotLive || seq != 0 || payload != "" {
				t.Fatalf("terminal %s bid: code=%s seq=%d payload=%q err=%v want ERR_NOT_LIVE/0/empty", status, code, seq, payload, err)
			}
			if got, _ := s.rdb.HGet(ctx, stateKey(aid), "seq").Int64(); got != 0 {
				t.Fatalf("terminal %s advanced seq=%d want 0", status, got)
			}
			events, _, err := s.ReadEventsAfter(ctx, aid, "")
			if err != nil {
				t.Fatal(err)
			}
			if len(events) != 0 {
				t.Fatalf("terminal %s wrote stream events: %+v", status, events)
			}
		})
	}
}
